language: node_js

node_js: lts

os: osx
osx_image: xcode8.2

install:
    - npm install
    - npm install npm@4.1.2
    - npm install appium@1.6.3

script:
    - npm run lint
    - npm run test

after_failure:
    - cat appium.log

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change

